Optimize the GUI front-end project structure
KKRainbow/EasyTier pull request #84
Opened 2024-05-05 15:45 UTC by m1m1sha

Can `pnpm` be used to replace `yarn`

2024-05-05 15:51 UTC, KKRainbow commented
what advantages do pnpm have over yarn

2024-05-05 15:55 UTC, KKRainbow commented
I have no preference between using yarn or pnpm. Use pnpm is okay for me if necessary.

2024-05-05 16:08 UTC, m1m1sha commented
> I have no preference between using yarn or pnpm. Use pnpm is okay for me if necessary.

i just providing an opinion, using pnpm or yarn is also acceptable for me
pnpm seems to be faster than yarn and can avoid duplicate package installations, but it doesn't seem to be fully compatible with yarn
﻿
im not particularly familiar with pr, so i may be a bit presumptuous in all aspects. if you have any questions, please point them out. this is also an opportunity for me to learn

thanks~

2024-05-06 01:26 UTC, KKRainbow commented
In my opinion it would be better to replace the package mgmt system in a new PR, because that change may require some modification in workflow and also make the PR too huge to review.

2024-05-06 03:15 UTC, m1m1sha commented
> In my opinion it would be better to replace the package mgmt system in a new PR, because that change may require some modification in github action workflow and also make the PR too huge to review.

okk, got it

2024-05-06 03:16 UTC, m1m1sha commented
i don't know how to make `vue office (volar)` use the formatting rules of `eslint`, so there are some slight differences between `vue office`'s formatting of `vue` files and `eslint` in the current pr

2024-05-06 05:00 UTC, KKRainbow commented
> i don't know how to make `vue office (volar)` use the formatting rules of `eslint`, so there are some slight differences between `vue office`'s formatting of `vue` files and `eslint` in the current pr

I'm not very familiar with vue things, but it looks like a minor and acceptable problem. may resolve it later.

2024-05-06 05:13 UTC, m1m1sha commented
> > i don't know how to make  use the formatting rules of , so there are some slight differences between 's formatting of  files and  in the current pr`vue office (volar)``eslint``vue office``vue``eslint`
> 
> I'm not very familiar with vue things, but it looks like a minor and acceptable problem. may resolve it later.

i have resolved it by using the workspace of vscode

2024-05-06 05:54 UTC, m1m1sha commented
@KKRainbow do you go through codacy static code analysis when submitting the front-end code?  i just split the code from the original files into their respective folders, and except for i18n loading logic, did not change the logic of other code. but it reported 95 issues.

although i think going through codacy review is a good thing, but i don't know how to use codacy to prompt me to modify the issue in local, there are no eslint errors or warnings in my local.  so i think it might be a bit troublesome, but I will try to modify it

2024-05-06 05:58 UTC, KKRainbow commented
> @KKRainbow do you go through codacy static code analysis when submitting the front-end code? i just split the code from the original files into their respective folders, and except for i18n loading logic, did not change the logic of other code. but it reported 95 issues.
> 
> although i think going through codacy review is a good thing, but i don't know how to use codacy to prompt me to modify the issue in local, there are no eslint errors or warnings in my local. so i think it might be a bit troublesome, but I will try to modify it

No, you can just ignore what Codacy is saying. I'm planning to remove this check because it doesn't provide enough useful warnings.

2024-05-06 06:22 UTC, KKRainbow commented
It need some time for me to review this change and I'll do that after work.

2024-05-06 06:27 UTC, m1m1sha commented
> It need some time for me to review this change and I'll do that after work.

okk

2024-05-06 15:52 UTC, KKRainbow commented on EasyTier.code-workspace
> +			"path": "."
如果 vscode 直接打开的是 easytier 项目的根目录，这个文件会影响 vscode 的行为么

2024-05-06 15:52 UTC, KKRainbow commented on easytier-gui/.gitignore
> +.vscode/
这里保持原有的 ./vscode/* 似乎会好些？

2024-05-06 15:52 UTC, KKRainbow commented on EasyTier.code-workspace
> +}
文件末尾留空行

2024-05-06 15:52 UTC, KKRainbow commented on easytier-gui/.npmrc
> +strict-peer-dependencies=false
文件末尾留空行

2024-05-06 15:52 UTC, KKRainbow commented on easytier-gui/.npmrc
> +strict-peer-dependencies=false
easytier-gui 依赖 yarn，也需要 npmrc 么

2024-05-06 15:52 UTC, KKRainbow commented on easytier-gui/.vscode/settings.json
> +  // Enable the ESlint flat config support
json 文件应该是不支持注释的，可以去掉注释

2024-05-06 15:52 UTC, KKRainbow commented on easytier-gui/src/auto-imports.d.ts
这个文件是如何生成的，后续如何保持这个文件是最新的呢

2024-05-06 15:52 UTC, KKRainbow commented on easytier-gui/src/main.ts
> +loadLanguageAsync(localStorage.getItem('lang') || 'en')
这个 async function 可以直接这么调用么，需要 await 不

2024-05-06 15:52 UTC, KKRainbow commented on easytier-gui/src/modules/i18n.ts
> +  localStorage.setItem('locale', lang)
这里是否需要改成 'lang'

2024-05-07 00:47 UTC, m1m1sha commented on EasyTier.code-workspace
> +			"path": "."
并不会，如果直接打开 easytier 根目录是和未添加工作区时是一样的
添加工作区是因为 easytier 的前端项目是作为子项目嵌套在文件夹内，有些插件无法正确发现嵌套文件夹项目，从而导致无法正常运行

2024-05-07 01:27 UTC, m1m1sha commented on easytier-gui/src/auto-imports.d.ts
这个是通过 `vite` 插件 `unplugin-auto-import` 自动生成的
后续启动前端项目时会自动生成，启动项目时修改前端文件也会自动更新

2024-05-07 01:27 UTC, m1m1sha commented on easytier-gui/.npmrc
> +strict-peer-dependencies=false
> easytier-gui 依赖 yarn，也需要 npmrc 么

yarn 使用 yarnrc.yml ，这个我先移除吧

2024-05-07 02:49 UTC, m1m1sha commented
eslint 配置项中 ignores 未生效，暂时使用命令行参数代替
使用 @eslint/config-inspector 能够解析发现 ignores 但是就是不生效，不知道是什么原因

2024-05-07 07:04 UTC, KKRainbow commented
main.ts 中直接调用 async 函数会执行么，那个是不是无效语句了成

2024-05-07 07:24 UTC, m1m1sha commented
> main.ts 中直接调用 async 函数会执行么，那个是不是无效语句了成

确实有些欠考虑，async 函数会执行但不会阻塞，如果函数运行时间比较长的话，有可能会导致 vue 挂载完成后还没执行完毕。但是在 async 函数内部的异步函数会正常阻塞直到完成后再进行下一步，我修改一下哈

2024-05-07 15:23 UTC, KKRainbow requested changes

2024-05-07 15:23 UTC, KKRainbow commented on easytier/src/common/config.rs
感觉好像没有 rebase 完全，这个文件的修改是 main 分支上的

2024-05-07 15:23 UTC, KKRainbow commented on easytier/src/common/config.rs
后面几个文件也是

2024-05-07 15:27 UTC, m1m1sha commented on easytier/src/common/config.rs
我看一下

2024-05-07 15:50 UTC, m1m1sha commented on easytier/src/common/config.rs
应该是因为我网络问题，修改没有完全更新全 :(
感觉我一直在重复合并冲突。。。

2024-05-07 16:04 UTC, m1m1sha commented
要不我重开一个pr？污染git记录了

2024-05-07 16:06 UTC, KKRainbow commented
> 要不我重开一个pr？污染git记录了

没事，你本地整好 force push 上来应该就行了

2024-05-07 16:24 UTC, KKRainbow approved these changes

2024-05-07 16:25 UTC, merged